### PR TITLE
Drop support for Python 3.5

### PR DESCRIPTION
**Pull request by bdrung**
Python 3.5 has reached end-of-life and `more-itertools` dropped support for it. Running the test suite for Python 3.5 fails:

```python
Traceback (most recent call last):
  File ".nox/tests-3-5/bin/coverage", line 8, in <module>
    sys.exit(main())
  File ".nox/tests-3-5/lib/python3.5/site-packages/coverage/cmdline.py", line 871, in main
    status = CoverageScript().command_line(argv)
  File ".nox/tests-3-5/lib/python3.5/site-packages/coverage/cmdline.py", line 588, in command_line
    return self.do_run(options, args)
  File ".nox/tests-3-5/lib/python3.5/site-packages/coverage/cmdline.py", line 746, in do_run
    runner.run()
  File ".nox/tests-3-5/lib/python3.5/site-packages/coverage/execfile.py", line 208, in run
    self._prepare2()
  File ".nox/tests-3-5/lib/python3.5/site-packages/coverage/execfile.py", line 168, in _prepare2
    pathname, self.package, self.spec = find_module(self.modulename)
  File ".nox/tests-3-5/lib/python3.5/site-packages/coverage/execfile.py", line 50, in find_module
    spec = importlib_util_find_spec(mod_main)
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/importlib/util.py", line 88, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
  File ".nox/tests-3-5/lib/python3.5/site-packages/pytest/__init__.py", line 37, in <module>
    from _pytest.python_api import approx
  File ".nox/tests-3-5/lib/python3.5/site-packages/_pytest/python_api.py", line 21, in <module>
    from more_itertools.more import always_iterable
  File ".nox/tests-3-5/lib/python3.5/site-packages/more_itertools/__init__.py", line 1, in <module>
    from .more import *  # noqa
  File ".nox/tests-3-5/lib/python3.5/site-packages/more_itertools/more.py", line 646
    f'Too few items in iterable (got {item_count})',
                                                  ^
SyntaxError: invalid syntax
```

So just drop support for Python 3.5.

### CODE REVIEW

**Comment by s0undt3ch** [comment]
Unfortunately, this project  is meant to be used with https://github.com/saltstack/pytest-salt-factories which in turn is to be used with https://github.com/saltstack/salt which cannot, **yet**, Python 3.5 support.

Closing.

**Comment by bdrung** [comment]
Then please fix the failing CI jobs for Python 3.5.

**Comment by s0undt3ch** [comment]
> Then please fix the failing CI jobs for Python 3.5.

Working on it

**Comment by s0undt3ch** [comment]
3.5 is now fixed in main branch

**Pull request closed without merging**
